### PR TITLE
Upgrade to Babel 6, and upgrade React + usage.

### PR DESCRIPTION
**Pull request by brev**
Upgrade to Babel 6, and upgrade React + usage. thanks!

### CODE REVIEW

**Comment by vanwagonet** [comment]
This looks awesome!

Babel 6 doesn't perform any transforms by default, so for this code to work as expected you need to set up a `.babelrc` file. Can you update the README to include the need for `.babelrc`?

**Comment by brev** [comment]
@thetalecrafter Updated: docs for Babel 6, more detailed examples, and `doctype` insertion when appropriate. Thanks for any feedback!

**Comment by vanwagonet** [comment]
LGTM

**Comment by brev** [comment]
thanks @thetalecrafter !

**Pull request merged**
